FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND pnpm-lock.yaml are copied
# where available (npm@5+)
COPY worker/package.json ./
COPY worker/pnpm-lock.yaml ./

RUN npm install

# Bundle app source
COPY worker/html2md.js .

CMD [ "node", "html2md.js" ]
